linters:
  rubocop:
    display_cop_names: true
    config: './rubocop.yml'

files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"

# find full documentation here: https://stickler-ci.com/docs